spring:
  quartz:
    job-store-type: jdbc # ????? memory ????????????????
    wait-for-jobs-to-complete-on-shutdown: true # ?????????
    overwrite-existing-jobs: true # ?????????
    jdbc:
      initialize-schema: never # ?????? SQL ??? Quartz ???
    properties: # quartz????
      org:
        quartz:
          scheduler:
            instanceName: scheduler # ???????
            instanceId: AUTO # ?????ID????
          # JobStore ????
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX # JobStore ???
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate # ??????JDBC???
            tablePrefix: QRTZ_ # Quartz ???
            useProperties: false # ???JobDataMap???????????
          # ???????
          threadPool:
            threadCount: 25 # ????????? 10 ?
            threadPriority: 5 # ?????
            class: org.quartz.simpl.SimpleThreadPool # ???????????????????????
